In [1]:
# Import dependencies
import pandas as pd
from pathlib import Path

In [2]:
# Files to Load
accident_path = Path("../Cleaned_Datasets/accident_cleaned.csv")
node_path = Path("../Cleaned_Datasets/node_cleaned.csv")
atmos_path = Path("../Cleaned_Datasets/atmospheric_cond_cleaned.csv")
surface_path = Path("../Cleaned_Datasets/road_surface_cond_cleaned.csv")

In [3]:
# Read the CSV file
accident_data = pd.read_csv(accident_path, low_memory=False)
node_data = pd.read_csv(node_path, low_memory=False)
atmos_data = pd.read_csv(atmos_path, low_memory=False)
surface_data = pd.read_csv(surface_path, low_memory=False)

In [4]:
# show accident df
accident_data_df = pd.DataFrame(accident_data)
accident_data_df.head()

,ACCIDENT_NO,ACCIDENTDATE,ACCIDENTTIME,ACCIDENT_TYPE,Accident Type Desc,DAY_OF_WEEK,Day Week Description,DCA_CODE,DCA Description,LIGHT_CONDITION,...,NO_PERSONS,NO_PERSONS_INJ_2,NO_PERSONS_INJ_3,NO_PERSONS_KILLED,NO_PERSONS_NOT_INJ,POLICE_ATTEND,ROAD_GEOMETRY,Road Geometry Desc,SEVERITY,SPEED_ZONE
0,T20060000010,13/01/2006,12:42:00,1,Collision with vehicle,6,Friday,113,RIGHT NEAR (INTERSECTIONS ONLY),1,...,6,0,1,0,5,1,1,Cross intersection,3,60
1,T20060000018,13/01/2006,19:10:00,1,Collision with vehicle,6,Friday,113,RIGHT NEAR (INTERSECTIONS ONLY),1,...,4,0,1,0,3,1,2,T intersection,3,70
2,T20060000022,14/01/2006,12:10:00,7,Fall from or in moving vehicle,7,Saturday,190,FELL IN/FROM VEHICLE,1,...,2,1,0,0,1,1,5,Not at intersection,2,100
3,T20060000023,14/01/2006,11:49:00,1,Collision with vehicle,7,Saturday,130,REAR END(VEHICLES IN SAME LANE),1,...,2,1,0,0,1,1,2,T intersection,2,80
4,T20060000026,14/01/2006,10:45:00,1,Collision with vehicle,7,Saturday,121,RIGHT THROUGH,1,...,3,0,3,0,0,1,5,Not at intersection,3,50

In [5]:
# List the columns
accident_data_df.dtypes

ACCIDENT_NO             object
ACCIDENTDATE            object
ACCIDENTTIME            object
ACCIDENT_TYPE            int64
Accident Type Desc      object
DAY_OF_WEEK              int64
Day Week Description    object
DCA_CODE                 int64
DCA Description         object
LIGHT_CONDITION          int64
Light Condition Desc    object
NO_OF_VEHICLES           int64
NO_PERSONS               int64
NO_PERSONS_INJ_2         int64
NO_PERSONS_INJ_3         int64
NO_PERSONS_KILLED        int64
NO_PERSONS_NOT_INJ       int64
POLICE_ATTEND            int64
ROAD_GEOMETRY            int64
Road Geometry Desc      object
SEVERITY                 int64
SPEED_ZONE               int64
dtype: object

In [6]:
# show node df
node_data_df = pd.DataFrame(node_data)
node_data_df.head()

,ACCIDENT_NO,NODE_ID,NODE_TYPE,LGA_NAME,REGION_NAME,DEG_URBAN_NAME,Lat,Long,POSTCODE_NO
0,T20060002689,22,I,MELBOURNE,METROPOLITAN NORTH WEST REGION,MELB_URBAN,-37.796596,144.951197,3051
1,T20060010827,22,I,MELBOURNE,METROPOLITAN NORTH WEST REGION,MELB_URBAN,-37.796596,144.951197,3051
2,T20060017279,22,I,MELBOURNE,METROPOLITAN NORTH WEST REGION,MELB_URBAN,-37.796596,144.951197,3051
3,T20060041762,22,I,MELBOURNE,METROPOLITAN NORTH WEST REGION,MELB_URBAN,-37.796596,144.951197,3051
4,T20060047478,22,I,MELBOURNE,METROPOLITAN NORTH WEST REGION,MELB_URBAN,-37.796596,144.951197,3051

In [7]:
# show atmos df
atmos_data_df = pd.DataFrame(atmos_data)
atmos_data_df.head()

    ACCIDENT_NO Atmosph_Cond_Desc
0  T20060000010             Clear
1  T20060000018             Clear
2  T20060000022             Clear
3  T20060000023             Clear
4  T20060000026             Clear

In [8]:
# show surface df
surface_data_df = pd.DataFrame(surface_data)
surface_data_df.head()

    ACCIDENT_NO Surface_Cond_Desc
0  T20060000010               Dry
1  T20060000018               Dry
2  T20060000022               Dry
3  T20060000023               Dry
4  T20060000026               Dry

In [9]:
# merge accident and node data
merge1_df = pd.merge(accident_data_df, node_data_df, on='ACCIDENT_NO', how='left')
merge1_df.head()

,ACCIDENT_NO,ACCIDENTDATE,ACCIDENTTIME,ACCIDENT_TYPE,Accident Type Desc,DAY_OF_WEEK,Day Week Description,DCA_CODE,DCA Description,LIGHT_CONDITION,...,SEVERITY,SPEED_ZONE,NODE_ID,NODE_TYPE,LGA_NAME,REGION_NAME,DEG_URBAN_NAME,Lat,Long,POSTCODE_NO
0,T20060000010,13/01/2006,12:42:00,1,Collision with vehicle,6,Friday,113,RIGHT NEAR (INTERSECTIONS ONLY),1,...,3,60,43078.0,I,DANDENONG,METROPOLITAN SOUTH EAST REGION,MELB_URBAN,-37.988622,145.218049,3175.0
1,T20060000018,13/01/2006,19:10:00,1,Collision with vehicle,6,Friday,113,RIGHT NEAR (INTERSECTIONS ONLY),1,...,3,70,29720.0,N,CASEY,METROPOLITAN SOUTH EAST REGION,MELB_URBAN,-37.990920,145.276320,3804.0
2,T20060000022,14/01/2006,12:10:00,7,Fall from or in moving vehicle,7,Saturday,190,FELL IN/FROM VEHICLE,1,...,2,100,203074.0,N,MORNINGTON PENINSULA,METROPOLITAN SOUTH EAST REGION,RURAL_VICTORIA,-38.396320,144.854890,3939.0
3,T20060000023,14/01/2006,11:49:00,1,Collision with vehicle,7,Saturday,130,REAR END(VEHICLES IN SAME LANE),1,...,2,80,55462.0,I,DANDENONG,METROPOLITAN SOUTH EAST REGION,MELB_URBAN,-37.989185,145.144961,3172.0
4,T20060000026,14/01/2006,10:45:00,1,Collision with vehicle,7,Saturday,121,RIGHT THROUGH,1,...,3,50,202988.0,N,MORNINGTON PENINSULA,METROPOLITAN SOUTH EAST REGION,MELB_URBAN,-38.372990,144.871594,3940.0

In [10]:
# merge accident, node and atmos data
merge2_df = pd.merge(merge1_df, atmos_data_df, on='ACCIDENT_NO', how='left')
merge2_df.head()

,ACCIDENT_NO,ACCIDENTDATE,ACCIDENTTIME,ACCIDENT_TYPE,Accident Type Desc,DAY_OF_WEEK,Day Week Description,DCA_CODE,DCA Description,LIGHT_CONDITION,...,SPEED_ZONE,NODE_ID,NODE_TYPE,LGA_NAME,REGION_NAME,DEG_URBAN_NAME,Lat,Long,POSTCODE_NO,Atmosph_Cond_Desc
0,T20060000010,13/01/2006,12:42:00,1,Collision with vehicle,6,Friday,113,RIGHT NEAR (INTERSECTIONS ONLY),1,...,60,43078.0,I,DANDENONG,METROPOLITAN SOUTH EAST REGION,MELB_URBAN,-37.988622,145.218049,3175.0,Clear
1,T20060000018,13/01/2006,19:10:00,1,Collision with vehicle,6,Friday,113,RIGHT NEAR (INTERSECTIONS ONLY),1,...,70,29720.0,N,CASEY,METROPOLITAN SOUTH EAST REGION,MELB_URBAN,-37.990920,145.276320,3804.0,Clear
2,T20060000022,14/01/2006,12:10:00,7,Fall from or in moving vehicle,7,Saturday,190,FELL IN/FROM VEHICLE,1,...,100,203074.0,N,MORNINGTON PENINSULA,METROPOLITAN SOUTH EAST REGION,RURAL_VICTORIA,-38.396320,144.854890,3939.0,Clear
3,T20060000023,14/01/2006,11:49:00,1,Collision with vehicle,7,Saturday,130,REAR END(VEHICLES IN SAME LANE),1,...,80,55462.0,I,DANDENONG,METROPOLITAN SOUTH EAST REGION,MELB_URBAN,-37.989185,145.144961,3172.0,Clear
4,T20060000026,14/01/2006,10:45:00,1,Collision with vehicle,7,Saturday,121,RIGHT THROUGH,1,...,50,202988.0,N,MORNINGTON PENINSULA,METROPOLITAN SOUTH EAST REGION,MELB_URBAN,-38.372990,144.871594,3940.0,Clear

In [11]:
# merge accident, node, atmos and surface data
merge3_df = pd.merge(merge2_df, surface_data_df, on='ACCIDENT_NO', how='left')
merge3_df

,ACCIDENT_NO,ACCIDENTDATE,ACCIDENTTIME,ACCIDENT_TYPE,Accident Type Desc,DAY_OF_WEEK,Day Week Description,DCA_CODE,DCA Description,LIGHT_CONDITION,...,NODE_ID,NODE_TYPE,LGA_NAME,REGION_NAME,DEG_URBAN_NAME,Lat,Long,POSTCODE_NO,Atmosph_Cond_Desc,Surface_Cond_Desc
0,T20060000010,13/01/2006,12:42:00,1,Collision with vehicle,6,Friday,113,RIGHT NEAR (INTERSECTIONS ONLY),1,...,43078.0,I,DANDENONG,METROPOLITAN SOUTH EAST REGION,MELB_URBAN,-37.988622,145.218049,3175.0,Clear,Dry
1,T20060000018,13/01/2006,19:10:00,1,Collision with vehicle,6,Friday,113,RIGHT NEAR (INTERSECTIONS ONLY),1,...,29720.0,N,CASEY,METROPOLITAN SOUTH EAST REGION,MELB_URBAN,-37.990920,145.276320,3804.0,Clear,Dry
2,T20060000022,14/01/2006,12:10:00,7,Fall from or in moving vehicle,7,Saturday,190,FELL IN/FROM VEHICLE,1,...,203074.0,N,MORNINGTON PENINSULA,METROPOLITAN SOUTH EAST REGION,RURAL_VICTORIA,-38.396320,144.854890,3939.0,Clear,Dry
3,T20060000023,14/01/2006,11:49:00,1,Collision with vehicle,7,Saturday,130,REAR END(VEHICLES IN SAME LANE),1,...,55462.0,I,DANDENONG,METROPOLITAN SOUTH EAST REGION,MELB_URBAN,-37.989185,145.144961,3172.0,Clear,Dry
4,T20060000026,14/01/2006,10:45:00,1,Collision with vehicle,7,Saturday,121,RIGHT THROUGH,1,...,202988.0,N,MORNINGTON PENINSULA,METROPOLITAN SOUTH EAST REGION,MELB_URBAN,-38.372990,144.871594,3940.0,Clear,Dry
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
203703,T20200019239,1/11/2020,12:11:00,1,Collision with vehicle,0,Sunday,142,LEAVING PARKING,1,...,665835.0,N,MELBOURNE,METROPOLITAN NORTH WEST REGION,MELB_URBAN,-37.828081,144.983214,3004.0,Clear,Dry
203704,T20200019247,1/11/2020,15:30:00,4,Collision with a fixed object,1,Sunday,171,LEFT OFF CARRIAGEWAY INTO OBJECT/PARKED VEHICL...,1,...,665912.0,N,GEELONG,SOUTH WESTERN REGION,TOWNS,-38.213352,144.443982,3224.0,Clear,Dry
203705,T20200019250,1/11/2020,18:00:00,1,Collision with vehicle,0,Sunday,116,LEFT NEAR (INTERSECTIONS ONLY),1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Clear,Dry
203706,T20200019253,1/11/2020,12:00:00,6,Vehicle overturned (no collision),1,Sunday,180,OFF CARRIAGEWAY ON RIGHT BEND,1,...,665836.0,N,EAST GIPPSLAND,EASTERN REGION,RURAL_VICTORIA,-36.965594,147.478154,3898.0,Clear,Dry
203707,T20200019417,4/11/2020,01:30:00,4,Collision with a fixed object,3,Wednesday,171,LEFT OFF CARRIAGEWAY INTO OBJECT/PARKED VEHICL...,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Clear,Dry

In [12]:
# List the columns
merge3_df.dtypes

ACCIDENT_NO              object
ACCIDENTDATE             object
ACCIDENTTIME             object
ACCIDENT_TYPE             int64
Accident Type Desc       object
DAY_OF_WEEK               int64
Day Week Description     object
DCA_CODE                  int64
DCA Description          object
LIGHT_CONDITION           int64
Light Condition Desc     object
NO_OF_VEHICLES            int64
NO_PERSONS                int64
NO_PERSONS_INJ_2          int64
NO_PERSONS_INJ_3          int64
NO_PERSONS_KILLED         int64
NO_PERSONS_NOT_INJ        int64
POLICE_ATTEND             int64
ROAD_GEOMETRY             int64
Road Geometry Desc       object
SEVERITY                  int64
SPEED_ZONE                int64
NODE_ID                 float64
NODE_TYPE                object
LGA_NAME                 object
REGION_NAME              object
DEG_URBAN_NAME           object
Lat                     float64
Long                    float64
POSTCODE_NO             float64
Atmosph_Cond_Desc        object
Surface_Cond_Desc        object
dtype: object

In [13]:
# Create a dictionary to specify the column name changes
new_column_names = {'Accident Type Desc': 'Accident_Type_Desc',
                    'Day Week Description': 'Day_Week_Description',
                    'DCA Description': 'DCA_Description',
                    'Light Condition Desc ': 'Light_Condition_Desc ',
                    'Road Geometry Desc ': 'Road_Geometry_Desc ',
                   }

# Use the rename method to rename columns
merge3_df.rename(columns=new_column_names, inplace=True)

# Display the DataFrame with renamed columns
merge3_df

,ACCIDENT_NO,ACCIDENTDATE,ACCIDENTTIME,ACCIDENT_TYPE,Accident_Type_Desc,DAY_OF_WEEK,Day_Week_Description,DCA_CODE,DCA_Description,LIGHT_CONDITION,...,NODE_ID,NODE_TYPE,LGA_NAME,REGION_NAME,DEG_URBAN_NAME,Lat,Long,POSTCODE_NO,Atmosph_Cond_Desc,Surface_Cond_Desc
0,T20060000010,13/01/2006,12:42:00,1,Collision with vehicle,6,Friday,113,RIGHT NEAR (INTERSECTIONS ONLY),1,...,43078.0,I,DANDENONG,METROPOLITAN SOUTH EAST REGION,MELB_URBAN,-37.988622,145.218049,3175.0,Clear,Dry
1,T20060000018,13/01/2006,19:10:00,1,Collision with vehicle,6,Friday,113,RIGHT NEAR (INTERSECTIONS ONLY),1,...,29720.0,N,CASEY,METROPOLITAN SOUTH EAST REGION,MELB_URBAN,-37.990920,145.276320,3804.0,Clear,Dry
2,T20060000022,14/01/2006,12:10:00,7,Fall from or in moving vehicle,7,Saturday,190,FELL IN/FROM VEHICLE,1,...,203074.0,N,MORNINGTON PENINSULA,METROPOLITAN SOUTH EAST REGION,RURAL_VICTORIA,-38.396320,144.854890,3939.0,Clear,Dry
3,T20060000023,14/01/2006,11:49:00,1,Collision with vehicle,7,Saturday,130,REAR END(VEHICLES IN SAME LANE),1,...,55462.0,I,DANDENONG,METROPOLITAN SOUTH EAST REGION,MELB_URBAN,-37.989185,145.144961,3172.0,Clear,Dry
4,T20060000026,14/01/2006,10:45:00,1,Collision with vehicle,7,Saturday,121,RIGHT THROUGH,1,...,202988.0,N,MORNINGTON PENINSULA,METROPOLITAN SOUTH EAST REGION,MELB_URBAN,-38.372990,144.871594,3940.0,Clear,Dry
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
203703,T20200019239,1/11/2020,12:11:00,1,Collision with vehicle,0,Sunday,142,LEAVING PARKING,1,...,665835.0,N,MELBOURNE,METROPOLITAN NORTH WEST REGION,MELB_URBAN,-37.828081,144.983214,3004.0,Clear,Dry
203704,T20200019247,1/11/2020,15:30:00,4,Collision with a fixed object,1,Sunday,171,LEFT OFF CARRIAGEWAY INTO OBJECT/PARKED VEHICL...,1,...,665912.0,N,GEELONG,SOUTH WESTERN REGION,TOWNS,-38.213352,144.443982,3224.0,Clear,Dry
203705,T20200019250,1/11/2020,18:00:00,1,Collision with vehicle,0,Sunday,116,LEFT NEAR (INTERSECTIONS ONLY),1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Clear,Dry
203706,T20200019253,1/11/2020,12:00:00,6,Vehicle overturned (no collision),1,Sunday,180,OFF CARRIAGEWAY ON RIGHT BEND,1,...,665836.0,N,EAST GIPPSLAND,EASTERN REGION,RURAL_VICTORIA,-36.965594,147.478154,3898.0,Clear,Dry
203707,T20200019417,4/11/2020,01:30:00,4,Collision with a fixed object,3,Wednesday,171,LEFT OFF CARRIAGEWAY INTO OBJECT/PARKED VEHICL...,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Clear,Dry

In [14]:
# Drop rows with NaN values in 'LGA_NAME'
column_name = 'LGA_NAME' 

merge3_df = merge3_df.dropna(subset=[column_name])

# Display the DataFrame after removing rows with NaN 
merge3_df

,ACCIDENT_NO,ACCIDENTDATE,ACCIDENTTIME,ACCIDENT_TYPE,Accident_Type_Desc,DAY_OF_WEEK,Day_Week_Description,DCA_CODE,DCA_Description,LIGHT_CONDITION,...,NODE_ID,NODE_TYPE,LGA_NAME,REGION_NAME,DEG_URBAN_NAME,Lat,Long,POSTCODE_NO,Atmosph_Cond_Desc,Surface_Cond_Desc
0,T20060000010,13/01/2006,12:42:00,1,Collision with vehicle,6,Friday,113,RIGHT NEAR (INTERSECTIONS ONLY),1,...,43078.0,I,DANDENONG,METROPOLITAN SOUTH EAST REGION,MELB_URBAN,-37.988622,145.218049,3175.0,Clear,Dry
1,T20060000018,13/01/2006,19:10:00,1,Collision with vehicle,6,Friday,113,RIGHT NEAR (INTERSECTIONS ONLY),1,...,29720.0,N,CASEY,METROPOLITAN SOUTH EAST REGION,MELB_URBAN,-37.990920,145.276320,3804.0,Clear,Dry
2,T20060000022,14/01/2006,12:10:00,7,Fall from or in moving vehicle,7,Saturday,190,FELL IN/FROM VEHICLE,1,...,203074.0,N,MORNINGTON PENINSULA,METROPOLITAN SOUTH EAST REGION,RURAL_VICTORIA,-38.396320,144.854890,3939.0,Clear,Dry
3,T20060000023,14/01/2006,11:49:00,1,Collision with vehicle,7,Saturday,130,REAR END(VEHICLES IN SAME LANE),1,...,55462.0,I,DANDENONG,METROPOLITAN SOUTH EAST REGION,MELB_URBAN,-37.989185,145.144961,3172.0,Clear,Dry
4,T20060000026,14/01/2006,10:45:00,1,Collision with vehicle,7,Saturday,121,RIGHT THROUGH,1,...,202988.0,N,MORNINGTON PENINSULA,METROPOLITAN SOUTH EAST REGION,MELB_URBAN,-38.372990,144.871594,3940.0,Clear,Dry
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
203701,T20200019125,30/10/2020,19:00:00,2,Struck Pedestrian,5,Friday,102,FAR SIDE. PED HIT BY VEHICLE FROM THE LEFT ...,2,...,665832.0,I,CASEY,METROPOLITAN SOUTH EAST REGION,MELB_URBAN,-38.032257,145.268088,3976.0,Not known,Wet
203702,T20200019195,31/10/2020,15:16:00,1,Collision with vehicle,6,Saturday,121,RIGHT THROUGH,1,...,37250.0,I,YARRA,METROPOLITAN NORTH WEST REGION,MELB_URBAN,-37.810825,145.003211,3067.0,Clear,Dry
203703,T20200019239,1/11/2020,12:11:00,1,Collision with vehicle,0,Sunday,142,LEAVING PARKING,1,...,665835.0,N,MELBOURNE,METROPOLITAN NORTH WEST REGION,MELB_URBAN,-37.828081,144.983214,3004.0,Clear,Dry
203704,T20200019247,1/11/2020,15:30:00,4,Collision with a fixed object,1,Sunday,171,LEFT OFF CARRIAGEWAY INTO OBJECT/PARKED VEHICL...,1,...,665912.0,N,GEELONG,SOUTH WESTERN REGION,TOWNS,-38.213352,144.443982,3224.0,Clear,Dry
203706,T20200019253,1/11/2020,12:00:00,6,Vehicle overturned (no collision),1,Sunday,180,OFF CARRIAGEWAY ON RIGHT BEND,1,...,665836.0,N,EAST GIPPSLAND,EASTERN REGION,RURAL_VICTORIA,-36.965594,147.478154,3898.0,Clear,Dry

In [15]:
# Storing file in Data folder
merged_data_output_path = Path("../Cleaned_Datasets/master_accident_cleaned.csv")
merge3_df.to_csv(merged_data_output_path, index=None, header=True)